let scanner=null,cameraRunning=false,completedBlob=null,downloadUrl=null;
let transfer={id:null,total:0,name:null,size:0,sha256:null,chunks:new Map(),duplicates:0,decoded:0,firstScan:null,lastScan:null};
const $=id=>document.getElementById(id);
function setMessage(text,type='info'){const m=$('message');m.textContent=text;m.className=`message ${type}`}
function formatBytes(n){if(!Number.isFinite(n))return '--';const u=['B','KB','MB','GB','TB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i===0?0:2)} ${u[i]}`}
function getMissing(){if(!transfer.total)return[];const a=[];for(let i=1;i<=transfer.total;i++)if(!transfer.chunks.has(i))a.push(i);return a}
function updateUI(){const r=transfer.chunks.size,t=transfer.total;const p=t?(100*r/t):0;$('progressText').textContent=`${r} / ${t||0}`;$('percentText').textContent=`${p.toFixed(1)}%`;$('progressFill').style.width=`${p}%`;$('fileName').textContent=transfer.name||'Waiting...';$('fileSize').textContent=transfer.size?formatBytes(transfer.size):'--';$('receivedFrames').textContent=r;$('missingFrames').textContent=t?getMissing().length:'--';$('duplicateFrames').textContent=transfer.duplicates;$('decodedCount').textContent=transfer.decoded;$('transferId').textContent=transfer.id||'--';$('sha256').textContent=transfer.sha256||'--';$('missingList').textContent=getMissing().length?getMissing().join(', '):'None';if(transfer.firstScan&&transfer.lastScan>transfer.firstScan){const fps=transfer.decoded/((transfer.lastScan-transfer.firstScan)/1000);$('scannerState').textContent=cameraRunning?`RUNNING (${fps.toFixed(2)} decoded fps)`:'STOPPED'}else $('scannerState').textContent=cameraRunning?'RUNNING':'STOPPED'}
function resetTransfer(silent=false){transfer={id:null,total:0,name:null,size:0,sha256:null,chunks:new Map(),duplicates:0,decoded:0,firstScan:null,lastScan:null};completedBlob=null;if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null}$('downloadButton').disabled=true;$('lastDecoded').textContent='Nothing decoded yet.';updateUI();if(!silent)setMessage('Transfer session reset.','info')}
function decodeBase64(t){const b=atob(t),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function sha256Hex(buffer){const d=await crypto.subtle.digest('SHA-256',buffer);return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function validatePacket(p){const req=['v','id','n','total','name','size','sha256','data'];if(!p||typeof p!=='object')throw Error('QR data is not an object.');for(const f of req)if(!(f in p))throw Error(`Missing field '${f}'.`);if(p.v!==1)throw Error(`Unsupported packet version: ${p.v}`);if(!Number.isInteger(p.n)||!Number.isInteger(p.total)||p.n<1||p.total<1||p.n>p.total)throw Error('Invalid frame numbering.')}
async function receivePacket(text){$('lastDecoded').textContent=text.slice(0,1000);transfer.decoded++;let p;try{p=JSON.parse(text)}catch{setMessage('QR decoded, but it is not the file-transfer JSON packet.','warning');updateUI();return}try{validatePacket(p)}catch(e){setMessage(e.message,'warning');updateUI();return}if(transfer.id===null){transfer.id=p.id;transfer.total=p.total;transfer.name=p.name;transfer.size=p.size;transfer.sha256=p.sha256;setMessage(`File detected: ${p.name} (${formatBytes(p.size)})`,'info')}if(p.id!==transfer.id){setMessage('A different transfer ID was detected. Press RESET before changing files.','warning');updateUI();return}if(transfer.chunks.has(p.n)){transfer.duplicates++;setMessage(`Frame ${p.n} repeated; duplicate ignored.`,'info');updateUI();return}let chunk;try{chunk=decodeBase64(p.data)}catch{setMessage(`Frame ${p.n} has invalid Base64 data.`,'warning');updateUI();return}transfer.chunks.set(p.n,chunk);const now=performance.now();if(!transfer.firstScan)transfer.firstScan=now;transfer.lastScan=now;updateUI();setMessage(`Frame ${p.n} received (${transfer.chunks.size}/${transfer.total}).`,'info');if(transfer.chunks.size===transfer.total)await reconstructFile()}
async function reconstructFile(){if(getMissing().length){setMessage(`Missing ${getMissing().length} frame(s).`,'warning');return}setMessage('All frames received. Reconstructing file...','info');let len=0;for(let i=1;i<=transfer.total;i++)len+=transfer.chunks.get(i).length;const out=new Uint8Array(len);let off=0;for(let i=1;i<=transfer.total;i++){const c=transfer.chunks.get(i);out.set(c,off);off+=c.length}if(out.length!==transfer.size){setMessage(`Size verification failed: received ${formatBytes(out.length)}, expected ${formatBytes(transfer.size)}.`,'error');return}try{const hash=await sha256Hex(out.buffer);if(hash.toLowerCase()!==transfer.sha256.toLowerCase()){setMessage('SHA-256 verification failed. The reconstructed file is corrupted/incomplete.','error');return}}catch(e){setMessage(`SHA-256 verification error: ${e.message}`,'error');return}completedBlob=new Blob([out],{type:'application/octet-stream'});if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(completedBlob);$('downloadButton').disabled=false;setMessage(`SUCCESS — ${transfer.name} received and SHA-256 verified.`,'success');updateUI()}
async function startCamera(){if(cameraRunning)return;if(typeof Html5Qrcode==='undefined'){setMessage('QR library did not load. Check Internet access and reload the page.','error');return}resetTransfer(true);scanner=new Html5Qrcode('reader');const config={fps:15,qrbox:(w,h)=>{const s=Math.floor(Math.min(w,h)*.85);return{width:Math.max(220,Math.min(s,550)),height:Math.max(220,Math.min(s,550))}},aspectRatio:1.0,disableFlip:true};try{$('cameraStatus').textContent='Requesting camera permission...';const cameras=await Html5Qrcode.getCameras();if(!cameras||cameras.length===0)throw Error('No camera was detected.');let selected=cameras[cameras.length-1];const preferred=cameras.find(c=>/back|rear|environment|main/i.test(c.label||''));if(preferred)selected=preferred;$('cameraName').textContent=selected.label||'Selected camera';await scanner.start(selected.id,config,async text=>{await receivePacket(text)},()=>{});cameraRunning=true;$('scannerState').textContent='RUNNING';$('startButton').disabled=true;$('stopButton').disabled=false;$('cameraStatus').textContent='Camera running. Now point the rear camera at the laptop QR.';setMessage('Receiver is ACTIVE. Start the laptop transmitter now.','success');updateUI()}catch(e){console.error(e);cameraRunning=false;$('cameraStatus').textContent='Camera could not be started.';$('scannerState').textContent='ERROR';setMessage(`Camera error: ${e.message||e}. Make sure camera permission is allowed and the page uses HTTPS.`,'error');try{await scanner.clear()}catch{}}}
async function stopCamera(){if(!scanner||!cameraRunning)return;try{await scanner.stop();await scanner.clear()}catch(e){console.error(e)}cameraRunning=false;$('startButton').disabled=false;$('stopButton').disabled=true;$('cameraStatus').textContent='Camera stopped.';$('scannerState').textContent='STOPPED';updateUI()}
function downloadFile(){if(!downloadUrl)return;const a=document.createElement('a');a.href=downloadUrl;a.download=transfer.name||'received_file';document.body.appendChild(a);a.click();a.remove()}
$('startButton').addEventListener('click',startCamera);$('stopButton').addEventListener('click',stopCamera);$('resetButton').addEventListener('click',async()=>{await stopCamera();resetTransfer()});$('downloadButton').addEventListener('click',downloadFile);resetTransfer(true);
