let stream=null,videoEl=null,workCanvas=null,workCtx=null,scanTimer=null,grayBuf=null,cameraRunning=false,completedBlob=null,downloadUrl=null,modeSetting='auto',detectedColors=null;
const SCHEMES={2:['L'],4:['R','B'],8:['R','G','B'],16:['R','GA','GB','B']},MODES=['auto',2,4,8,16],MAX_SCAN_WIDTH=1600;
let transfer={id:null,total:0,name:null,size:0,sha256:null,chunks:new Map(),duplicates:0,decoded:0,firstScan:null,lastScan:null};
const $=id=>document.getElementById(id);
function setMessage(text,type='info'){const m=$('message');m.textContent=text;m.className=`message ${type}`}
function formatBytes(n){if(!Number.isFinite(n))return '--';const u=['B','KB','MB','GB','TB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i===0?0:2)} ${u[i]}`}
function getMissing(){if(!transfer.total)return[];const a=[];for(let i=1;i<=transfer.total;i++)if(!transfer.chunks.has(i))a.push(i);return a}
function updateUI(){const r=transfer.chunks.size,t=transfer.total;const p=t?(100*r/t):0;$('progressText').textContent=`${r} / ${t||0}`;$('percentText').textContent=`${p.toFixed(1)}%`;$('progressFill').style.width=`${p}%`;$('fileName').textContent=transfer.name||'Waiting...';$('fileSize').textContent=transfer.size?formatBytes(transfer.size):'--';$('receivedFrames').textContent=r;$('missingFrames').textContent=t?getMissing().length:'--';$('duplicateFrames').textContent=transfer.duplicates;$('decodedCount').textContent=transfer.decoded;$('transferId').textContent=transfer.id||'--';$('sha256').textContent=transfer.sha256||'--';$('missingList').textContent=getMissing().length?getMissing().join(', '):'None';if(transfer.firstScan&&transfer.lastScan>transfer.firstScan){const fps=transfer.decoded/((transfer.lastScan-transfer.firstScan)/1000);$('scannerState').textContent=cameraRunning?`RUNNING (${fps.toFixed(2)} decoded fps)`:'STOPPED'}else $('scannerState').textContent=cameraRunning?'RUNNING':'STOPPED'}
function resetTransfer(silent=false){transfer={id:null,total:0,name:null,size:0,sha256:null,chunks:new Map(),duplicates:0,decoded:0,firstScan:null,lastScan:null};completedBlob=null;detectedColors=null;if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null}$('downloadButton').disabled=true;$('lastDecoded').textContent='Nothing decoded yet.';updateUI();if(!silent)setMessage('Transfer session reset.','info')}
function decodeBase64(t){const b=atob(t),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
async function sha256Hex(buffer){const d=await crypto.subtle.digest('SHA-256',buffer);return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function validatePacket(p){const req=['v','id','n','total','name','size','sha256','data'];if(!p||typeof p!=='object')throw Error('QR data is not an object.');for(const f of req)if(!(f in p))throw Error(`Missing field '${f}'.`);if(p.v!==1)throw Error(`Unsupported packet version: ${p.v}`);if(!Number.isInteger(p.n)||!Number.isInteger(p.total)||p.n<1||p.total<1||p.n>p.total)throw Error('Invalid frame numbering.')}
async function receivePacket(text){$('lastDecoded').textContent=text.slice(0,1000);transfer.decoded++;let p;try{p=JSON.parse(text)}catch{setMessage('QR decoded, but it is not the file-transfer JSON packet.','warning');updateUI();return}try{validatePacket(p)}catch(e){setMessage(e.message,'warning');updateUI();return}if(modeSetting==='auto'&&detectedColors===null)detectedColors=[4,8,16].includes(p.c)?p.c:2;if(transfer.id===null){transfer.id=p.id;transfer.total=p.total;transfer.name=p.name;transfer.size=p.size;transfer.sha256=p.sha256;setMessage(`File detected: ${p.name} (${formatBytes(p.size)})`,'info')}if(p.id!==transfer.id){setMessage('A different transfer ID was detected. Press RESET before changing files.','warning');updateUI();return}if(transfer.chunks.has(p.n)){transfer.duplicates++;setMessage(`Frame ${p.n} repeated; duplicate ignored.`,'info');updateUI();return}let chunk;try{chunk=decodeBase64(p.data)}catch{setMessage(`Frame ${p.n} has invalid Base64 data.`,'warning');updateUI();return}transfer.chunks.set(p.n,chunk);const now=performance.now();if(!transfer.firstScan)transfer.firstScan=now;transfer.lastScan=now;updateUI();setMessage(`Frame ${p.n} received (${transfer.chunks.size}/${transfer.total}).`,'info');if(transfer.chunks.size===transfer.total)await reconstructFile()}
async function reconstructFile(){if(getMissing().length){setMessage(`Missing ${getMissing().length} frame(s).`,'warning');return}setMessage('All frames received. Reconstructing file...','info');let len=0;for(let i=1;i<=transfer.total;i++)len+=transfer.chunks.get(i).length;const out=new Uint8Array(len);let off=0;for(let i=1;i<=transfer.total;i++){const c=transfer.chunks.get(i);out.set(c,off);off+=c.length}if(out.length!==transfer.size){setMessage(`Size verification failed: received ${formatBytes(out.length)}, expected ${formatBytes(transfer.size)}.`,'error');return}try{const hash=await sha256Hex(out.buffer);if(hash.toLowerCase()!==transfer.sha256.toLowerCase()){setMessage('SHA-256 verification failed. The reconstructed file is corrupted/incomplete.','error');return}}catch(e){setMessage(`SHA-256 verification error: ${e.message}`,'error');return}completedBlob=new Blob([out],{type:'application/octet-stream'});if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(completedBlob);$('downloadButton').disabled=false;setMessage(`SUCCESS — ${transfer.name} received and SHA-256 verified.`,'success');updateUI()}
function layerToGray(data,n,kind){if(!grayBuf||grayBuf.length!==n*4)grayBuf=new Uint8ClampedArray(n*4);const c=kind==='R'?0:(kind==='B'?2:1),mode=kind==='GA'?'A':(kind==='GB'?'B':'soft');const hist=new Uint32Array(256);for(let i=0,j=c;i<n;i++,j+=4)hist[data[j]]++;const cut=n*0.01;let lo=0,hi=255,acc=0;while(lo<255&&(acc+=hist[lo])<cut)lo++;acc=0;while(hi>0&&(acc+=hist[hi])<cut)hi--;const range=Math.max(1,hi-lo);for(let i=0,j=c,k=0;i<n;i++,j+=4,k+=4){let v=(data[j]-lo)*255/range;if(v<0)v=0;else if(v>255)v=255;if(mode==='A')v=v<128?0:255;else if(mode==='B')v=(v>=43&&v<=212)?0:255;grayBuf[k]=v;grayBuf[k+1]=v;grayBuf[k+2]=v;grayBuf[k+3]=255}return grayBuf}
function activeLayers(){if(modeSetting!=='auto')return SCHEMES[modeSetting];if(detectedColors)return SCHEMES[detectedColors];return['L','R','GA','GB','B']}
function decodeFrame(img){const{data,width:w,height:h}=img;const out=[],seen=new Set(),opts={inversionAttempts:'dontInvert'},n=w*h;for(const kind of activeLayers()){const r=kind==='L'?jsQR(data,w,h,opts):jsQR(layerToGray(data,n,kind),w,h,opts);if(r&&r.data&&!seen.has(r.data)){seen.add(r.data);out.push(r.data)}}return out}
async function scanLoop(){if(!cameraRunning)return;try{if(videoEl&&videoEl.readyState>=2&&videoEl.videoWidth){const vw=videoEl.videoWidth,vh=videoEl.videoHeight,sc=Math.min(1,MAX_SCAN_WIDTH/vw),w=Math.round(vw*sc),h=Math.round(vh*sc);if(workCanvas.width!==w||workCanvas.height!==h){workCanvas.width=w;workCanvas.height=h}workCtx.drawImage(videoEl,0,0,w,h);const found=decodeFrame(workCtx.getImageData(0,0,w,h));for(const t of found)await receivePacket(t)}}catch(e){console.error(e)}if(cameraRunning)scanTimer=setTimeout(scanLoop,10)}
function releaseCamera(){if(scanTimer){clearTimeout(scanTimer);scanTimer=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(videoEl){videoEl.srcObject=null;videoEl.remove();videoEl=null}}
async function startCamera(){if(cameraRunning)return;if(typeof jsQR==='undefined'){setMessage('QR library did not load. Check Internet access and reload the page.','error');return}resetTransfer(true);try{$('cameraStatus').textContent='Requesting camera permission...';if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw Error('Camera API unavailable (HTTPS required).');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});const track=stream.getVideoTracks()[0];try{await track.applyConstraints({advanced:[{focusMode:'continuous'}]})}catch{}$('cameraName').textContent=track.label||'Selected camera';const reader=$('reader');reader.innerHTML='';videoEl=document.createElement('video');videoEl.setAttribute('playsinline','');videoEl.muted=true;videoEl.srcObject=stream;reader.appendChild(videoEl);await videoEl.play();workCanvas=document.createElement('canvas');workCtx=workCanvas.getContext('2d',{willReadFrequently:true});cameraRunning=true;$('scannerState').textContent='RUNNING';$('startButton').disabled=true;$('stopButton').disabled=false;$('cameraStatus').textContent='Camera running. Now point the rear camera at the laptop QR.';setMessage('Receiver is ACTIVE. Start the laptop transmitter now.','success');updateUI();scanLoop()}catch(e){console.error(e);cameraRunning=false;releaseCamera();$('cameraStatus').textContent='Camera could not be started.';$('scannerState').textContent='ERROR';setMessage(`Camera error: ${e.message||e}. Make sure camera permission is allowed and the page uses HTTPS.`,'error')}}
async function stopCamera(){if(!cameraRunning)return;cameraRunning=false;releaseCamera();$('startButton').disabled=false;$('stopButton').disabled=true;$('cameraStatus').textContent='Camera stopped.';$('scannerState').textContent='STOPPED';updateUI()}
function toggleMode(){modeSetting=MODES[(MODES.indexOf(modeSetting)+1)%MODES.length];detectedColors=null;$('modeButton').textContent=modeSetting==='auto'?'MODE: AUTO':`MODE: ${modeSetting} COLORS${modeSetting===2?' (B/W)':''}`;setMessage(modeSetting==='auto'?'Auto mode: the color scheme is detected from the first decoded frame.':`Fixed mode: decoding ${modeSetting}-color frames. The laptop must use the same scheme.`,'info')}
function downloadFile(){if(!downloadUrl)return;const a=document.createElement('a');a.href=downloadUrl;a.download=transfer.name||'received_file';document.body.appendChild(a);a.click();a.remove()}
$('startButton').addEventListener('click',startCamera);$('stopButton').addEventListener('click',stopCamera);$('resetButton').addEventListener('click',async()=>{await stopCamera();resetTransfer()});$('downloadButton').addEventListener('click',downloadFile);$('modeButton').addEventListener('click',toggleMode);resetTransfer(true);
